db:
  type: mysql:10.4
  disk: 2048
cache:
  type: redis:5.0
# -SOLR- uncomment if using solr
# solrsearch:
#     type: solr:8.4
#     disk: 1024
#     configuration:
#       configsets:
#         mainconfig: !archive "configsets/ext_solr_11_0_0"
#       cores:
#         core_en:
#           core_properties: |
#             configSet=mainconfig
#             schema=english/schema.xml
#         core_sv:
#           core_properties: |
#             configSet=mainconfig
#             schema=swedish/schema.xml
#         core_de:
#           core_properties: |
#             configSet=mainconfig
#             schema=german/schema.xml
#         core_no:
#           core_properties: |
#             configSet=mainconfig
#             schema=norwegian/schema.xml
#         core_da:
#           core_properties: |
#             configSet=mainconfig
#             schema=danish/schema.xml
#         core_fr:
#           core_properties: |
#             configSet=mainconfig
#             schema=french/schema.xml
#       endpoints:
#         main:
#           core: core_en
#         site2:
#           core: core_sv
