version: "3.7"

services:

  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: ${DB_IMAGE:-mariadb:10.3}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-1234}
    volumes:
      - db:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  web:
    container_name: ${COMPOSE_PROJECT_NAME}_web
    image: ${WEB_IMAGE:-t3kit/10-php7.4-fpm-nginx-buster:1.1.2}
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_1},${VIRTUAL_HOST_2:?err}

      - VIRTUAL_HOST_1=http://${VIRTUAL_HOST_1}
      - VIRTUAL_HOST_2=http://${VIRTUAL_HOST_2}

      - SOLR_CORE_EN=core_en
      - SOLR_CORE_SV=core_sv
      - SOLR_CORE_DE=core_de
      - SOLR_CORE_NO=core_no
      - SOLR_CORE_DA=core_da
      - SOLR_CORE_FR=core_fr
      - SOLR_HOST_MAIN=${COMPOSE_PROJECT_NAME}_solr
      - SOLR_HOST_SITE2=${COMPOSE_PROJECT_NAME}_solr
      - SOLR_PORT=${SOLR_PORT:-8983}

      - TYPO3_CONTEXT=${TYPO3_CONTEXT:-Development/local}

      - DB_HOST=${COMPOSE_PROJECT_NAME}_db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-1234}
      - DB_NAME=${DB_NAME:-t3kit10}
      - DB_USER=${DB_USER:-root}

      - USER_ID=${USER_ID:-1000}
    volumes:
      - ../../:/var/www/html:${FILE_SYSTEM_MODE:-delegated}
      - type: volume
        source: var
        target: /var/www/html/var
      - type: volume
        source: typo3temp
        target: /var/www/html/public/typo3temp

  solr:
    container_name: ${COMPOSE_PROJECT_NAME}_solr
    image: typo3solr/ext-solr:11.0.3
    ports:
      - "${SOLR_PORT:-8983}:8983"
    volumes:
      - solr:/var/solr

networks:
  default:
    external:
      name: nproxy

volumes:
  typo3temp:
    name: ${COMPOSE_PROJECT_NAME}_typo3temp
  var:
    name: ${COMPOSE_PROJECT_NAME}_var
  db:
    name: ${COMPOSE_PROJECT_NAME}_db
  solr:
    name: ${COMPOSE_PROJECT_NAME}_solr



