version: "3.8"

services:

  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: ${DB_IMAGE}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-1234}
    volumes:
      - db:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  web:
    container_name: ${COMPOSE_PROJECT_NAME}_web
    image: ${WEB_IMAGE}
    env_file:
      - ../../.env
    volumes:
      - type: bind
        source: ../../
        target: /var/www/html
      - type: volume
        source: var
        target: /var/www/html/var
      - type: volume
        source: typo3temp
        target: /var/www/html/public/typo3temp

networks:
  default:
    external:
      name: nproxy

volumes:
  typo3temp:
    name: ${COMPOSE_PROJECT_NAME}_typo3temp
  var:
    name: ${COMPOSE_PROJECT_NAME}_var
  db:
    name: ${COMPOSE_PROJECT_NAME}_db
