version: "3.7"

services:

  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: ${DB_IMAGE:-mariadb:10.3}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-1234}
    volumes:
      - db:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  web:
    container_name: ${COMPOSE_PROJECT_NAME}_web
    image: ${WEB_IMAGE:-t3kit/10-php7.4-fpm-nginx-buster:1.1.1}
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_1},${VIRTUAL_HOST_2}

      - PLATFORM_ROUTES_MAIN=http://${VIRTUAL_HOST_1}
      - PLATFORM_ROUTES_SITE2=http://${VIRTUAL_HOST_2}

      - TYPO3_CONTEXT=${TYPO3_CONTEXT:-Development/local}

      - DB_HOST=${COMPOSE_PROJECT_NAME}_db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-1234}
      - DB_NAME=${DB_NAME:-t3kit10}
      - DB_USER=${DB_USER:-root}

      - USER_ID=${USER_ID:-1000}
    volumes:
      - ./conf.d/:/etc/nginx/conf.d:${FILE_SYSTEM_MODE:-delegated}
      - ../../../public/fileadmin/:/var/www/html/public/fileadmin:${FILE_SYSTEM_MODE:-delegated}
      - ../../../.localconf/:/var/www/html/.localconf:${FILE_SYSTEM_MODE:-delegated}
      - type: bind
        source: ../../../
        target: /var/www/html
        read_only: true
        consistency: ${FILE_SYSTEM_MODE:-delegated}
      - type: volume
        source: var
        target: /var/www/html/var
      - type: volume
        source: typo3temp
        target: /var/www/html/public/typo3temp

networks:
  default:
    external:
      name: nproxy

volumes:
  typo3temp:
    name: ${COMPOSE_PROJECT_NAME}_typo3temp
  var:
    name: ${COMPOSE_PROJECT_NAME}_var
  db:
    name: ${COMPOSE_PROJECT_NAME}_db



